#! /bin/bash

ENV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "$1" != "--seeqBuild" ] ; then

  echo "Adding Java Development Kit (JDK) to path"
  . "$ENV_DIR/jdk/environment.sh"

  echo "Adding Maven to path"
  . "$ENV_DIR/maven/environment.sh"

fi

export M2_REPO=$ENV_DIR/.m2/repository
echo Maven repository will be "$M2_REPO"

export SEEQ_CONNECTOR_SDK_HOME=$ENV_DIR

export SEEQ_CONNECTOR_NAME="$(ls -d -- *seeq-link-connector*)"

echo "<settings><localRepository>$SEEQ_CONNECTOR_SDK_HOME/.m2/repository</localRepository></settings>" >"$SEEQ_CONNECTOR_SDK_HOME/maven-settings.xml"

export PATH=$ENV_DIR:$PATH
export PS1="\[\033[1;35m\]Seeq Connector SDK Java Dev Environment  \[\033[0;33m\]\w\[\033[0m\]\n\\\$ "

echo ""
echo "Seeq Connector SDK Java development environment is set up."
echo ""
echo "Your connector name is currently \"$SEEQ_CONNECTOR_NAME\""
echo ""
echo "First, execute \"build\" to compile the connector."
echo "Then execute \"ide\" to launch Eclipse for development and debugging."
echo "Finally, execute \"package\" to build a deployable connector package."
echo ""
