#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -z "$SEEQ_CONNECTOR_SDK_HOME" ] ; then
  echo ""
  echo "You're not in the Connector SDK Dev Environment."
  echo "Execute '. environment' first"
  echo ""
  exit 1
fi 

if [ ! -e "$SEEQ_CONNECTOR_SDK_HOME/seeq-link-sdk-debugging-agent/.project" ] ; then
  echo ""
  echo "You must build the projects successfully before launching Eclipse."
  echo "Execute 'build' first."
  echo ""
  exit 1
fi

ECLIPSE_SETTINGS_DIR__MAVEN="$SEEQ_CONNECTOR_SDK_HOME/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings"
if [ ! -e "$ECLIPSE_SETTINGS_DIR__MAVEN" ] ; then mkdir -p "$ECLIPSE_SETTINGS_DIR__MAVEN" ; fi

SEEQ_CONNECTOR_SDK_HOME__ESCAPED_FOR_ECLIPSE="$SEEQ_CONNECTOR_SDK_HOME"

echo "eclipse.m2.userSettingsFile=$SEEQ_CONNECTOR_SDK_HOME__ESCAPED_FOR_ECLIPSE/maven-settings.xml" >"$ECLIPSE_SETTINGS_DIR__MAVEN/org.eclipse.m2e.core.prefs"

SEEQ_ECLIPSE_COMMAND="$SEEQ_CONNECTOR_SDK_HOME/eclipse/eclipse"
if [ ! -x $SEEQ_ECLIPSE_COMMAND ] ; then
  # try the OSX path name
  SEEQ_ECLIPSE_COMMAND="$SEEQ_CONNECTOR_SDK_HOME/eclipse/Eclipse.app/Contents/MacOS/eclipse"
fi

"$SEEQ_ECLIPSE_COMMAND" -data "$SEEQ_CONNECTOR_SDK_HOME/workspace" -import "$SEEQ_CONNECTOR_SDK_HOME"
