#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -z "$SEEQ_CONNECTOR_SDK_HOME" ] ; then
  echo ""
  echo "You're not in the Connector SDK Dev Environment."
  echo "Execute '. environment' first"
  echo ""
  exit 1
fi 

java -cp "$DIR/seeq-link-sdk-debugging-agent/target/lib/seeq-link-sdk-50.4.4-v202103021828.jar" com.seeq.link.sdk.utilities.ConnectorPackager "$SEEQ_CONNECTOR_NAME/target" "packages/$SEEQ_CONNECTOR_NAME"
