{
  "formatVersion": "1.1",
  "component": {
    "group": "com.seeq.link",
    "module": "jvm-link",
    "version": "50.4.4-v202103021828",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "fasozsz7undk3phlrn3lwfwxaq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jvm-link-50.4.4-v202103021828.jar",
          "url": "jvm-link-50.4.4-v202103021828.jar",
          "size": 261,
          "sha512": "76d12ef4917322b2200a2a2b9dc3b32d09a45ea49cc58bbfbcd5fc5fb8d16e076ba2a19ec143e26d724ae3f6c76919bebb5e42d033862a55e2fd723366e67870",
          "sha256": "b91fe68b5e980eece84f36efcb4d39c5e32dace9e311c98aa426af77a3da385d",
          "sha1": "e6b17e5dc916e756abf5a277a45f1dd364db24c2",
          "md5": "93c5d87b70bd272cf0aae8b1f228b4ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jvm-link-50.4.4-v202103021828.jar",
          "url": "jvm-link-50.4.4-v202103021828.jar",
          "size": 261,
          "sha512": "76d12ef4917322b2200a2a2b9dc3b32d09a45ea49cc58bbfbcd5fc5fb8d16e076ba2a19ec143e26d724ae3f6c76919bebb5e42d033862a55e2fd723366e67870",
          "sha256": "b91fe68b5e980eece84f36efcb4d39c5e32dace9e311c98aa426af77a3da385d",
          "sha1": "e6b17e5dc916e756abf5a277a45f1dd364db24c2",
          "md5": "93c5d87b70bd272cf0aae8b1f228b4ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jvm-link-50.4.4-v202103021828-sources.jar",
          "url": "jvm-link-50.4.4-v202103021828-sources.jar",
          "size": 261,
          "sha512": "e5fb313c98b12e8dddb8e5a8c019c84f7e8056e7efaff2827813ce65741aaf870ca86870a4ce34f4eb84df8ff9d7bca5925d2e3159824aeed55669c51d577bf9",
          "sha256": "70d5eab45f820a3624c745ee17939219a3e059aeca650e2c091291947d834380",
          "sha1": "04db3b6652613a9f7b29f497e4f33ef74d67c23b",
          "md5": "784b06343d7e059c14591e3580eff095"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jvm-link-50.4.4-v202103021828-javadoc.jar",
          "url": "jvm-link-50.4.4-v202103021828-javadoc.jar",
          "size": 261,
          "sha512": "76d12ef4917322b2200a2a2b9dc3b32d09a45ea49cc58bbfbcd5fc5fb8d16e076ba2a19ec143e26d724ae3f6c76919bebb5e42d033862a55e2fd723366e67870",
          "sha256": "b91fe68b5e980eece84f36efcb4d39c5e32dace9e311c98aa426af77a3da385d",
          "sha1": "e6b17e5dc916e756abf5a277a45f1dd364db24c2",
          "md5": "93c5d87b70bd272cf0aae8b1f228b4ad"
        }
      ]
    }
  ]
}
