{
  "formatVersion": "1.1",
  "component": {
    "group": "com.seeq.link",
    "module": "seeq-link-sdk",
    "version": "50.4.4-v202103021828",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "fasozsz7undk3phlrn3lwfwxaq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.seeq.utilities",
          "module": "seeq-utilities",
          "version": {
            "requires": "50.4.4-v202103021828"
          }
        },
        {
          "group": "com.seeq",
          "module": "seeq-sdk",
          "version": {
            "requires": "50.4.4-v202103021828"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "seeq-link-sdk-50.4.4-v202103021828.jar",
          "url": "seeq-link-sdk-50.4.4-v202103021828.jar",
          "size": 1361466,
          "sha512": "be4a2303b9538599e11de9a27e548c2f96c482b65251c2b69cf0885b7592d2bddfb8819ff02098a3b5169a5e5e2b7b1c85f17c2ebd375a1ce04029f156a1323a",
          "sha256": "0e2dc8b0ac34d6b8c1c1da93fe75c9b6448b1db75186353b642e74b20b938d5a",
          "sha1": "36e2822bec314f2686dbfb50fffa6b2831febe5a",
          "md5": "59fcfe47a4e36db3252dddb221a27e96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.github.jbellis",
          "module": "jamm",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "annotations",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark",
          "version": {
            "requires": "0.18.9"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark-ext-toc",
          "version": {
            "requires": "0.18.9"
          }
        },
        {
          "group": "com.seeq.utilities",
          "module": "seeq-utilities",
          "version": {
            "requires": "50.4.4-v202103021828"
          }
        },
        {
          "group": "com.seeq",
          "module": "seeq-sdk",
          "version": {
            "requires": "50.4.4-v202103021828"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "seeq-link-sdk-50.4.4-v202103021828.jar",
          "url": "seeq-link-sdk-50.4.4-v202103021828.jar",
          "size": 1361466,
          "sha512": "be4a2303b9538599e11de9a27e548c2f96c482b65251c2b69cf0885b7592d2bddfb8819ff02098a3b5169a5e5e2b7b1c85f17c2ebd375a1ce04029f156a1323a",
          "sha256": "0e2dc8b0ac34d6b8c1c1da93fe75c9b6448b1db75186353b642e74b20b938d5a",
          "sha1": "36e2822bec314f2686dbfb50fffa6b2831febe5a",
          "md5": "59fcfe47a4e36db3252dddb221a27e96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "seeq-link-sdk-50.4.4-v202103021828-sources.jar",
          "url": "seeq-link-sdk-50.4.4-v202103021828-sources.jar",
          "size": 103781,
          "sha512": "474c4486c0ccbc23a5195458f0e99bddc8abb27b181953ee686eed40f4cf0dec2930cba855ee922c30a70dc5f33d7d695bcb1e30285bff56648a9ca93b002b8d",
          "sha256": "f8178abf6593aab1b86efee4d479b1b9f31be51d6ba1ad16ed6cf75bb7633e8e",
          "sha1": "865ead5b75ad3c2c7a2ee5df0c18c3315d24268e",
          "md5": "5818d738d14057b69c382c4837975222"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "seeq-link-sdk-50.4.4-v202103021828-javadoc.jar",
          "url": "seeq-link-sdk-50.4.4-v202103021828-javadoc.jar",
          "size": 1536756,
          "sha512": "9af866f6ba18fee251b38c9ef0a8c32d00e9172ff75c73cb2e720ac0704827cc829dd109ae0a2663443506463d3d58fdadeb69a084014fdd4ddb3bddd1c39bdb",
          "sha256": "6c6e5f192f7a8c90e593d6ade42fa85dc8afa3a2263fa4e401203abe04501305",
          "sha1": "2ea8b51617f81c2d940f457d19eb706567153c70",
          "md5": "db133d350527afa7b3882ec9bc622c57"
        },
        {
          "name": "seeq-link-sdk-50.4.4-v202103021828-javadoc.jar",
          "url": "seeq-link-sdk-50.4.4-v202103021828-javadoc.jar",
          "size": 1536756,
          "sha512": "9af866f6ba18fee251b38c9ef0a8c32d00e9172ff75c73cb2e720ac0704827cc829dd109ae0a2663443506463d3d58fdadeb69a084014fdd4ddb3bddd1c39bdb",
          "sha256": "6c6e5f192f7a8c90e593d6ade42fa85dc8afa3a2263fa4e401203abe04501305",
          "sha1": "2ea8b51617f81c2d940f457d19eb706567153c70",
          "md5": "db133d350527afa7b3882ec9bc622c57"
        }
      ]
    }
  ]
}
