{
  "formatVersion": "1.1",
  "component": {
    "group": "com.seeq.link",
    "module": "seeq-link-agent",
    "version": "50.4.4-v202103021828",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "fasozsz7undk3phlrn3lwfwxaq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.seeq.utilities",
          "module": "seeq-utilities",
          "version": {
            "requires": "50.4.4-v202103021828"
          }
        },
        {
          "group": "com.seeq",
          "module": "seeq-sdk",
          "version": {
            "requires": "50.4.4-v202103021828"
          }
        }
      ],
      "files": [
        {
          "name": "seeq-link-agent-50.4.4-v202103021828.jar",
          "url": "seeq-link-agent-50.4.4-v202103021828.jar",
          "size": 174543,
          "sha512": "303d346662c7b4abe56092892316d12f0b9d4c2b0c99cabaa07776095f02fcda4b771f4fe1e785c29cf943b1682499f0c44f0cde0f7847a358d4c3cf7709356f",
          "sha256": "2f1dfdeafd06ed807c1621880fbf19c0b554c4d6907f9fdb2bcfee3c9703ae94",
          "sha1": "f090c3abd45afc41682dc02a91fe447b24fb0d85",
          "md5": "fe5ca8e5c4516d73ecb75cd6775ddec1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.github.jbellis",
          "module": "jamm",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "annotations",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.seeq.link",
          "module": "seeq-link-sdk",
          "version": {
            "requires": "50.4.4-v202103021828"
          }
        },
        {
          "group": "com.seeq.shaded",
          "module": "shaded-websocket-client",
          "version": {
            "requires": "9.4.19.v20190610-shade-1"
          }
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "uk.org.lidalia",
          "module": "sysout-over-slf4j",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-json-jackson",
          "version": {
            "requires": "2.27"
          }
        },
        {
          "group": "com.seeq.utilities",
          "module": "seeq-utilities",
          "version": {
            "requires": "50.4.4-v202103021828"
          }
        },
        {
          "group": "com.seeq",
          "module": "seeq-sdk",
          "version": {
            "requires": "50.4.4-v202103021828"
          }
        }
      ],
      "files": [
        {
          "name": "seeq-link-agent-50.4.4-v202103021828.jar",
          "url": "seeq-link-agent-50.4.4-v202103021828.jar",
          "size": 174543,
          "sha512": "303d346662c7b4abe56092892316d12f0b9d4c2b0c99cabaa07776095f02fcda4b771f4fe1e785c29cf943b1682499f0c44f0cde0f7847a358d4c3cf7709356f",
          "sha256": "2f1dfdeafd06ed807c1621880fbf19c0b554c4d6907f9fdb2bcfee3c9703ae94",
          "sha1": "f090c3abd45afc41682dc02a91fe447b24fb0d85",
          "md5": "fe5ca8e5c4516d73ecb75cd6775ddec1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "seeq-link-agent-50.4.4-v202103021828-sources.jar",
          "url": "seeq-link-agent-50.4.4-v202103021828-sources.jar",
          "size": 44722,
          "sha512": "74708bc3ed8a6ab83c0571cd61bec02623fbc2084ed955c8ea9604a3ae7aea252c2d2c62191cfe4781d8992b7a2040b55bc969f60a5ddb50c3f30602fb4c8cbd",
          "sha256": "8c5af648721b5f358001cb0cb24fdaf9b04459cb0f121317dbe5940ba6088331",
          "sha1": "7e1ccd7b0c216b9a55142bc429e621d3348bb4f2",
          "md5": "2c3b4fd1557effa67de4a53ef4f006b6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "seeq-link-agent-50.4.4-v202103021828-javadoc.jar",
          "url": "seeq-link-agent-50.4.4-v202103021828-javadoc.jar",
          "size": 513999,
          "sha512": "dbf356f880e43ef5ed24291b50ef6f9838f73d3313a086c9551db01954af595e1726388e4f80970b979750c27d48c751ae669d3f1e459c90e33dc29dc2f0420a",
          "sha256": "641f3bbd347bf47ed624c3e3dfa13437a439c0d5ab63a79559a38ac60b8cd28b",
          "sha1": "fcffb642908fd27dd4b812d778c791eda9313fbb",
          "md5": "804b73a6e2ad26046607ec80c374bdcf"
        }
      ]
    }
  ]
}
